
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hertada
 */
public class dlMedia_205314159_Dito extends javax.swing.JDialog {

    private ArrayList<Media_205314159_Dito> tempMed;
    DefaultTableModel tabelModel;
    TableColumnModel columnModel;

    /**
     * Creates new form tDialog
     */
    public dlMedia_205314159_Dito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public dlMedia_205314159_Dito(java.awt.Frame parent, boolean modal, String command, ArrayList<Media_205314159_Dito> list) {
        super(parent, modal);
        initComponents();
        tempMed = list;
        multiButton.setText(command);
        if (multiButton.getText().equals("Cari Data")) {
            koranButt.setEnabled(false);
            tabloButt.setEnabled(false);
            majButt.setEnabled(false);
            alamatTF.setEnabled(false);
            redakTF.setEnabled(false);
            tahunTF.setEnabled(false);
            spinnerTF1.setEnabled(false);
            spinnerTF2.setEnabled(false);
        } else {
            koranButt.setEnabled(true);
            tabloButt.setEnabled(true);
            majButt.setEnabled(true);
            alamatTF.setEnabled(true);
            redakTF.setEnabled(true);
            tahunTF.setEnabled(true);
            spinnerTF1.setEnabled(true);
            spinnerTF2.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        noL = new javax.swing.JLabel();
        namaL = new javax.swing.JLabel();
        alamatL = new javax.swing.JLabel();
        redakL = new javax.swing.JLabel();
        tahunL = new javax.swing.JLabel();
        spinnerL1 = new javax.swing.JLabel();
        spinnerL2 = new javax.swing.JLabel();
        noTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        alamatTF = new javax.swing.JTextField();
        redakTF = new javax.swing.JTextField();
        tahunTF = new javax.swing.JTextField();
        spinnerTF1 = new javax.swing.JTextField();
        spinnerTF2 = new javax.swing.JTextField();
        multiButton = new javax.swing.JButton();
        noCB = new javax.swing.JCheckBox();
        namaCB = new javax.swing.JCheckBox();
        redakCB = new javax.swing.JCheckBox();
        alamatCB = new javax.swing.JCheckBox();
        tahunCB = new javax.swing.JCheckBox();
        spin1CB = new javax.swing.JCheckBox();
        spin2CB = new javax.swing.JCheckBox();
        koranButt = new javax.swing.JRadioButton();
        tabloButt = new javax.swing.JRadioButton();
        majButt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Isi / Cari / Hapus / Data Media - 205314159");

        noL.setText("Nop Ijin");

        namaL.setText("Nama");

        alamatL.setText("Alamat");

        redakL.setText("Redaktur");

        tahunL.setText("Tahun Berdiri         ");

        spinnerL1.setText("Bahasa");

        spinnerL2.setText("Iklan");

        noTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                noTFFocusLost(evt);
            }
        });

        namaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaTFFocusLost(evt);
            }
        });

        alamatTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alamatTFFocusLost(evt);
            }
        });

        redakTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                redakTFFocusLost(evt);
            }
        });

        tahunTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahunTFFocusLost(evt);
            }
        });

        spinnerTF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinnerTF1FocusLost(evt);
            }
        });

        spinnerTF2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spinnerTF2FocusLost(evt);
            }
        });

        multiButton.setText("Isi Data / Hapus Data / Cari Data");
        multiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiButtonActionPerformed(evt);
            }
        });

        noCB.setText("Format Benar");

        namaCB.setText("Format Benar");

        redakCB.setText("Format Benar");

        alamatCB.setText("Format Benar");

        tahunCB.setText("Format Benar");

        spin1CB.setText("Format Benar");

        spin2CB.setText("Format Benar");

        buttonGroup1.add(koranButt);
        koranButt.setSelected(true);
        koranButt.setText("Koran");
        koranButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koranButtActionPerformed(evt);
            }
        });

        buttonGroup1.add(tabloButt);
        tabloButt.setText("Tabloid");
        tabloButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabloButtActionPerformed(evt);
            }
        });

        buttonGroup1.add(majButt);
        majButt.setText("Majalah");
        majButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noL)
                            .addComponent(namaL)
                            .addComponent(alamatL)
                            .addComponent(redakL)
                            .addComponent(tahunL)
                            .addComponent(spinnerL1)
                            .addComponent(spinnerL2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(koranButt)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noTF)
                                    .addComponent(namaTF)
                                    .addComponent(alamatTF)
                                    .addComponent(redakTF)
                                    .addComponent(tahunTF)
                                    .addComponent(spinnerTF1)
                                    .addComponent(spinnerTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noCB)
                                    .addComponent(namaCB)
                                    .addComponent(alamatCB)
                                    .addComponent(redakCB)
                                    .addComponent(tahunCB)
                                    .addComponent(spin1CB)
                                    .addComponent(spin2CB)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tabloButt)
                                .addGap(18, 18, 18)
                                .addComponent(majButt)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(koranButt)
                    .addComponent(tabloButt)
                    .addComponent(majButt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noL)
                    .addComponent(noTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaL)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatL)
                    .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redakL)
                    .addComponent(redakTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redakCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunL)
                    .addComponent(tahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerL1)
                    .addComponent(spinnerTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin1CB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerL2)
                    .addComponent(spinnerTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin2CB))
                .addGap(18, 18, 18)
                .addComponent(multiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiButtonActionPerformed
        // TODO add your handling code here:

        String id = noTF.getText();
        String nama = namaTF.getText();
        String alamat = alamatTF.getText();
        String hobi = redakTF.getText();
        String spin1 = spinnerTF1.getText();
        String spin2 = spinnerTF2.getText();

        Media_205314159_Dito newMed = null;

        if (multiButton.getText().equals("Isi Data")) {
            try {
                int tahun = Integer.parseInt(tahunTF.getText());
                LocalDate thn = LocalDate.ofYearDay(tahun, 1);
                if (koranButt.isSelected()) {
                    int temp = Integer.parseInt(spin2);
                    LocalDate ikln = LocalDate.ofYearDay(temp, 1);
                    newMed = new Koran_205314159_Dito(id, nama, alamat, hobi, thn, spin1, ikln);
                } else if (tabloButt.isSelected()) {
                    newMed = new Tabloid_205314159_Dito(id, nama, alamat, hobi, thn, spin1, spin2);
                } else {
                    newMed = new Majalah_205314159_Dito(id, nama, alamat, hobi, thn, spin1, spin2);
                }
                tempMed.add(newMed);
                dispose();
                JOptionPane.showMessageDialog(null, "Media Berhasil ditambahkan", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            //Cari data
            for (int i = 0; i < tempMed.size(); i++) {
                Media_205314159_Dito check = tempMed.get(i);
                if (check.getNoIjin().equalsIgnoreCase(id)) {
                    JOptionPane.showMessageDialog(null, "Data Nomor Ketemu di No: " + (i + 1), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    return;
                } else if (check.getNama().equalsIgnoreCase(nama)) {
                    JOptionPane.showMessageDialog(null, "Data Nama Ketemu di No: " + (i + 1), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    return;
                }
            }
            
//            for (int i = 0; i < tempMed.size(); i++) {
//                Media_205314159_Dito check = tempMed.get(i);
//                if (check.getNoIjin().equalsIgnoreCase(id)) {
//                    JOptionPane.showMessageDialog(null, "Data Ketemu di Nomor: " + (i + 1), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
//                    dispose();
//                    return;
//                } else if (check.getNama().equalsIgnoreCase(nama)) {
//                    JOptionPane.showMessageDialog(null, "Data Ketemu di Nomor: " + (i + 1), "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
//                    dispose();
//                    return;
//                }
//            }
            JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_multiButtonActionPerformed

    private void noTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noTFFocusLost
        // TODO add your handling code here:
        if (noTF.getText().isEmpty()) {
            noCB.setSelected(true);
            return;
        }
        String cek = noTF.getText();
        if (!cek.matches("(\\w{2})\\-(\\w{1}\\d{3})\\-(\\d{3})")) {
            try {
                throw new Exception("Nomor harus sesuai!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                noCB.setSelected(false);
                return;
            }
        } else {
            noCB.setSelected(true);
        }


    }//GEN-LAST:event_noTFFocusLost

    private void namaTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaTFFocusLost
        // TODO add your handling code here:
        if (namaTF.getText().isEmpty()) {
            namaCB.setSelected(false);
            return;
        }
        String cek = namaTF.getText();
        if (cek.matches(".*\\d.*")) {
            try {
                throw new Exception("Nama mengandung angka");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                namaCB.setSelected(false);
                return;
            }
        } else {
            namaCB.setSelected(true);
        }
    }//GEN-LAST:event_namaTFFocusLost

    private void alamatTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alamatTFFocusLost
        // TODO add your handling code here:
        if (alamatTF.getText().isEmpty()) {
            alamatCB.setSelected(false);
            return;
        } else {
            alamatCB.setSelected(true);
        }
    }//GEN-LAST:event_alamatTFFocusLost

    private void redakTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_redakTFFocusLost
        // TODO add your handling code here:
        if (redakCB.getText().isEmpty()) {
            redakCB.setSelected(false);
            return;
        } else {
            redakCB.setSelected(true);
        }
    }//GEN-LAST:event_redakTFFocusLost

    private void tahunTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunTFFocusLost
        // TODO add your handling code here:
        if (tahunTF.getText().isEmpty()) {
            tahunCB.setSelected(false);
            return;
        }
        String cek = tahunTF.getText();
        if (!(cek.matches("2\\d{3,}"))) {
            try {
                throw new Exception("Input 4 Digit dan Diatas tahun 2000");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                tahunCB.setSelected(false);
                return;
            }
        } else {
            tahunCB.setSelected(true);
        }
    }//GEN-LAST:event_tahunTFFocusLost

    private void spinnerTF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerTF1FocusLost
        // TODO add your handling code here:
        if (spinnerTF1.getText().isEmpty()) {
            spin1CB.setSelected(false);
            return;
        } else {
            spin1CB.setSelected(true);
        }
    }//GEN-LAST:event_spinnerTF1FocusLost

    private void spinnerTF2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinnerTF2FocusLost
        // TODO add your handling code here:
        if (spinnerTF2.getText().isEmpty()) {
            spin2CB.setSelected(false);
            return;
        }
        String cek = spinnerTF2.getText();
        if (!(cek.matches("\\d+"))) {
            try {
                throw new Exception("Harus berupa angka");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                spin2CB.setSelected(false);
                return;
            }
        } else {
            spin2CB.setSelected(true);
        }
    }//GEN-LAST:event_spinnerTF2FocusLost

    private void tabloButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabloButtActionPerformed
        // TODO add your handling code here:
        spinnerL1.setText("Topik");
        spinnerL2.setText("Halaman");
    }//GEN-LAST:event_tabloButtActionPerformed

    private void majButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majButtActionPerformed
        // TODO add your handling code here:
        spinnerL1.setText("Kategori");
        spinnerL2.setText("Volume");
    }//GEN-LAST:event_majButtActionPerformed

    private void koranButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koranButtActionPerformed
        // TODO add your handling code here:
        spinnerL1.setText("Bahasa");
        spinnerL2.setText("Iklan");
    }//GEN-LAST:event_koranButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlMedia_205314159_Dito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlMedia_205314159_Dito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlMedia_205314159_Dito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlMedia_205314159_Dito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlMedia_205314159_Dito dialog = new dlMedia_205314159_Dito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alamatCB;
    private javax.swing.JLabel alamatL;
    private javax.swing.JTextField alamatTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton koranButt;
    private javax.swing.JRadioButton majButt;
    private javax.swing.JButton multiButton;
    private javax.swing.JCheckBox namaCB;
    private javax.swing.JLabel namaL;
    private javax.swing.JTextField namaTF;
    private javax.swing.JCheckBox noCB;
    private javax.swing.JLabel noL;
    private javax.swing.JTextField noTF;
    private javax.swing.JCheckBox redakCB;
    private javax.swing.JLabel redakL;
    private javax.swing.JTextField redakTF;
    private javax.swing.JCheckBox spin1CB;
    private javax.swing.JCheckBox spin2CB;
    private javax.swing.JLabel spinnerL1;
    private javax.swing.JLabel spinnerL2;
    private javax.swing.JTextField spinnerTF1;
    private javax.swing.JTextField spinnerTF2;
    private javax.swing.JRadioButton tabloButt;
    private javax.swing.JCheckBox tahunCB;
    private javax.swing.JLabel tahunL;
    private javax.swing.JTextField tahunTF;
    // End of variables declaration//GEN-END:variables
}
